DesafioAgroTools/DesafioAgroTools/Controllers/HomeController.cs
using DesafioAgroToolsDomain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioAgroTools.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesafioAgroTools/DesafioAgroTools/Controllers/QuestionController.cs
using DesafioAgroToolsDomain.Models;
using DesafioAgroToolsInfra.Context;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioAgroTools.Controllers
{
    public class QuestionController : Controller
    {
        ApplicationContext _context;
        public QuestionController(ApplicationContext context)
        {
            _context = context;
        }
        // GET: QuestionController
        public ActionResult Index()
        {
            return View();
        }

        // GET: QuestionController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: QuestionController/Create
        public ActionResult Create()
        {
            var idQuestionary = (int)TempData["IdQuestionary"];
            ViewBag.IdQuestionary = idQuestionary;
            var questionsAdicionadas = _context.Question.Where(x => x.QuestionaryId == idQuestionary).ToList();
            return View(questionsAdicionadas);
        }

        // POST: QuestionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            try
            {
                _context.Add(question);
                _context.SaveChanges();
                ViewBag.IdQuestionary = question.QuestionaryId;
                var questionsAdicionadas = _context.Question.Where(x => x.QuestionaryId == question.QuestionaryId).ToList();
                return View(questionsAdicionadas);
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: QuestionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: QuestionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DesafioAgroTools/DesafioAgroTools/Controllers/QuestionaryController.cs
using DesafioAgroToolsDomain.Models;
using DesafioAgroToolsDomain.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioAgroTools.Controllers
{
    public class QuestionaryController : Controller
    {
        private QuestionaryService _questionaryService;
        public QuestionaryController(QuestionaryService questionaryService)
        {
            _questionaryService = questionaryService;
        }
        // GET: QuestionaryController
        public ActionResult Index()
        {

            //Acessar o domain e trazer a lista de Models
            //var models = _questionaryDomain.GetAllQuestionaries();
            //return View(models);

            
            return View(_questionaryService.GetAll());
        }

        // GET: QuestionaryController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: QuestionaryController/Create
        public ActionResult Create()
        {
            
            return View(new Questionary());
        }

        // POST: QuestionaryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Questionary questionary)
        {
            
            try
            {
                _questionaryService.Add(questionary);
                TempData["IdQuestionary"] = questionary.Id;
                return RedirectToAction("Create","Question");
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionaryController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: QuestionaryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionaryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: QuestionaryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DesafioAgroTools/DesafioAgroTools/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <p>AgroTools</p>
</div>

DesafioAgroTools/DesafioAgroTools/Views/Question/Create.cshtml
@model List<Question>
@{
    ViewData["Title"] = "Criar Questões";
}

<div class="text-center panel panel-primary">
    <h1 class="display-4 ">Nova Questão</h1>

    <div class="panel-body">

        @using (Html.BeginForm("Create", "Question", FormMethod.Post))
        {
            <div class="form-inline">
                <div class="form-group col-md-5">
                    Pergunta
                    <br />
                    @Html.TextBox("Description",null, htmlAttributes : new { @class = "form-control", id = "Title" })
                    <input name="QuestionaryId" id="QuestionaryId" type="number" hidden value="@ViewBag.IdQuestionary" />

                </div>
            </div>
            <br />
            <br />
            <div class="btn-group  pull-right">
                @Html.ActionLink("Concluir", "Index", "Questionary", new { @class = "btn btn-default" })
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        }

    </div>


    <table class="table">
        <tr scope="col">
            <th>Description</th>
            <th>Ações</th>
        </tr>
        @foreach (var model in Model)
        {
            <tr scope="row">
                <td>@Html.DisplayFor(modelItem => model.Description)</td>
                <td>@Html.ActionLink("Excluir", "DeleteQuestion", new { idQuestion = model.Id })</td>
            </tr>
        }

    </table>


</div>

</div>

DesafioAgroTools/DesafioAgroTools/Views/Question/Index.cshtml
@model List<Question>
@{
    ViewData["Title"] = "Questões";
}

<div class="text-center">
    <h1 class="display-4">Questões</h1>



    @Html.ActionLink("Adicionar", "Create")

    <table>
        <tr>
            <th>Questões</th>
            <th>Acoes</th>
        </tr>
        @foreach (var model in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => model.Description)</td>
                <td>@Html.ActionLink("Excluir", "DeleteQuestion", new { idQuestionary = model.Id })</td>
            </tr>
        }

    </table>


</div>

DesafioAgroTools/DesafioAgroTools/Views/Questionary/Create.cshtml
@model Questionary
@{
    ViewData["Title"] = "Criar Questionario";
}

<div class="text-center panel panel-primary">
    <h1 class="display-4 ">Criar Questionario</h1>

    <div class="panel-body">
        @using (Html.BeginForm("Create", "Questionary", FormMethod.Post))
        {
            <div class="form-inline">
                <div class="form-group col-md-5">
                    Titulo
                    <br />
                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control", id = "Title" })
                </div>
                <div class="form-group col-md-5">
                    User
                    <br />
                    @Html.TextBoxFor(model => model.User, new { @class = "form-control", id = "User" })
                </div>
            </div>
            <br />


            <div class="btn-group pull-right" style="margin-top:30px">
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>

        }
    </div>
    </div>

DesafioAgroTools/DesafioAgroTools/Views/Questionary/Index.cshtml
@model List<Questionary>
@{
    ViewData["Title"] = "Questionarios";
}

<div class="text-center">
    <h1 class="display-4">Questionario</h1>



    @Html.ActionLink("Adicionar", "Create")

    <table class="table">
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">User</thscope="col">
            <th scope="col">Acoes</th>
        </tr>
        @foreach (var model in Model)
        {
            <tr scope="row">
                <td>@Html.DisplayFor(modelItem => model.Title)</td>
                <td>@Html.DisplayFor(modelItem => model.User)</td>
                <td>@Html.ActionLink("Responder", "AnswerQuestion", new { idQuestionary = model.Id })</td>
            </tr>
        }

     </table>


    </div>

DesafioAgroTools/DesafioAgroTools/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesafioAgroTools</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesafioAgroTools</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Questionary" asp-action="Index">Questionarário</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DesafioAgroTools - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>